// Copyright Svh03ra (C) 2026, All rights reserved
// Source File: doom_wad_data.c, embedded DOOM1.WAD image for the kernel.
//
// This includes the DOOM 1997 source code, written by id Software Inc. Please check the license in the current folder.
// This repository is licensed under the GNU General Public License.
//
// The DOOM1.WAD ships INSIDE the kernel image as a plain data array, so
// the game data is always present on ANY boot media - USB/Ventoy, CD,
// hard disk - with zero bus I/O at boot. The Makefile generates the
// byte-array source from the real WAD file (doom_wad_data.c.generated)
// during the build; the placeholder below only keeps the symbol defined
// so the kernel still links without a WAD present (the DOOM app then
// shows the missing-WAD error window, exactly like before).
//
// The array is 16-byte aligned and declared as real data (not a bss
// hole): the array size in the header is what limits doom_wad_pread.

#include "doom_wad_embed.h"

#ifndef DOOM_WAD_DATA_INCLUDED
#define DOOM_WAD_DATA_INCLUDED

/* Placeholder definitions (used verbatim when no WAD ships): zero size,
 * so doom_wad_embed_get reports "no embedded image" and the reader falls
 * back to the multiboot module / ATA / ATAPI media as before. The
 * Makefile replaces this file with the generated byte-array source when
 * a WAD is embedded. */
__attribute__((aligned(16), used))
const uint8_t doom_wad_data[1] = { 0 };
const uint32_t doom_wad_data_size = 0;

#endif /* DOOM_WAD_DATA_INCLUDED */
