// Copyright Svh03ra (C) 2026, All rights reserved
// Source File: doom_wad_embed.h, embedded DOOM1.WAD access for the kernel.
//
// This includes the DOOM 1997 source code, written by id Software Inc. Please check the license in the current folder.
// This repository is licensed under the GNU General Public License.
//
// Declares the byte array that doom_wad_data.c (Makefile-generated) adds
// to the kernel image. The WAD reader (doom_libc.c) prefers this always-
// present RAM copy over ATA/ATAPI bus reads, so the game data is
// available on ANY boot media - USB/Ventoy, CD, hard disk.

#ifndef DOOM_WAD_EMBED_H
#define DOOM_WAD_EMBED_H

#include <stdint.h>

/* Defined in doom_wad_data.c (generated by the Makefile from the real
 * DOOM1.WAD; a 0-byte placeholder when no WAD is shipped). */
extern const uint8_t doom_wad_data[];
extern const uint32_t doom_wad_data_size;

#endif /* DOOM_WAD_EMBED_H */
