#!/usr/bin/env python3
# Copyright Svh03ra (C) 2026, All rights reserved
# Tool: mkcrashtable.py - generate the crash-handler symbol table.
#
# This repository is licensed under the GNU General Public License.
#
# Usage: mkcrashtable.py <kernel.bin> <out-dir> [--max N] [--empty]
#
# Writes two files into <out-dir>:
#
#   crash_symbols.h  Stable declarations: the entry type, the fixed table
#                    size and the extern table/count. Its content never
#                    depends on the kernel, so the kernel translation unit
#                    is NOT recompiled when the symbol data changes.
#   crash_symbols.c  The data itself: exactly CRASH_SYMBOL_MAX entries
#                    (unused slots zero-filled) plus the real entry count.
#                    The entry count is always the same fixed size, so
#                    filling in real symbols never moves a single kernel
#                    address - one kernel link is enough (no recompile).
#
# Speed: the previous shell implementation spawned `addr2line` once per
# symbol (400 processes, ~56 s on a slow filesystem). This tool runs one
# nm and one addr2line for the whole table (~0.3 s).
#
# Both files are written only when their content actually changes, so an
# unchanged build never touches the kernel's dependencies.

import os
import subprocess
import sys

DEFAULT_MAX = 400


def parse_args(argv):
    if len(argv) < 3:
        sys.stderr.write(__doc__)
        raise SystemExit(2)

    kernel = argv[1]
    out_dir = argv[2]
    limit = DEFAULT_MAX
    force_empty = False

    rest = argv[3:]
    i = 0
    while i < len(rest):
        if rest[i] == "--max" and i + 1 < len(rest):
            limit = int(rest[i + 1])
            i += 2
            continue
        if rest[i] == "--empty":
            force_empty = True
            i += 1
            continue
        sys.stderr.write("mkcrashtable.py: unknown option %s\n" % rest[i])
        raise SystemExit(2)

    return kernel, out_dir, limit, force_empty


def write_if_changed(path, text):
    try:
        with open(path, "r", encoding="utf-8") as handle:
            if handle.read() == text:
                return False
    except FileNotFoundError:
        pass

    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as handle:
        handle.write(text)
    os.replace(tmp, path)
    return True


def header_text(limit):
    return "".join([
        "/* Generated by tools/mkcrashtable.py - do not edit. */\n",
        "#ifndef HALOXOS_CRASH_SYMBOLS_GENERATED_H\n",
        "#define HALOXOS_CRASH_SYMBOLS_GENERATED_H\n",
        "\n",
        "#define CRASH_SYMBOL_MAX %d\n" % limit,
        "\n",
        "typedef struct {\n",
        "    unsigned long addr;\n",
        "    const char *name;\n",
        "    const char *file;\n",
        "    int line;\n",
        "} CrashSymbolEntry;\n",
        "\n",
        "extern const int crash_symbol_count;\n",
        "extern const CrashSymbolEntry crash_symbol_table_data[CRASH_SYMBOL_MAX];\n",
        "\n",
        "#endif\n",
    ])


def data_text(entries, limit):
    lines = [
        "/* Generated by tools/mkcrashtable.py - do not edit. */\n",
        "#include \"crash_symbols.h\"\n\n",
        "const int crash_symbol_count = %d;\n\n" % len(entries),
        "const CrashSymbolEntry crash_symbol_table_data[CRASH_SYMBOL_MAX] = {\n",
    ]

    for entry in entries:
        lines.append('    { 0x%08x, "%s", "%s", %d },\n' % entry)

    # Pad to the fixed size so the table never changes shape between the
    # layout link and the symbol-refresh link.
    for _ in range(limit - len(entries)):
        lines.append("    { 0, 0, 0, 0 },\n")

    lines.append("};\n")
    return "".join(lines)


def c_string(value):
    out = []
    for ch in value:
        if ch in ('"', "\\"):
            out.append("\\" + ch)
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            out.append("?")
    return "".join(out)


def run(command):
    return subprocess.run(command, capture_output=True, text=True, errors="replace").stdout


def collect_symbols(kernel, limit):
    symbols = []
    for line in run(["nm", "-n", "--defined-only", kernel]).splitlines():
        parts = line.split(None, 2)
        if len(parts) != 3:
            continue
        addr, kind, name = parts
        if kind not in "tTdDrRbB" or not name:
            continue
        try:
            value = int(addr, 16)
        except ValueError:
            continue
        symbols.append((value, name))
        if len(symbols) >= limit:
            break
    return symbols


def normalize_file(path):
    if not path or path.startswith("?"):
        return "unknown"

    marker = "/HaloxOS/"
    index = path.rfind(marker)
    if index >= 0:
        path = path[index + len(marker):]

    while "/../" in path:
        head, _, tail = path.partition("/../")
        parent = head.rsplit("/", 1)[0] if "/" in head else ""
        path = (parent + "/" + tail) if parent else tail

    while path.startswith("../"):
        path = path[3:]

    if path.startswith("?") or "/" not in path:
        return "unknown"
    return "HaloxOS/" + path


def split_location(location):
    location = location.replace(" (discriminator ", " (").strip()
    if " (discriminator" in location:
        location = location.split(" (discriminator")[0]

    if ":" not in location:
        return location, 0

    path, _, tail = location.rpartition(":")
    if not tail.isdigit():
        return path, 0
    return path, int(tail)


def resolve_symbols(kernel, symbols):
    if not symbols:
        return []

    addresses = ["0x%08x" % addr for addr, _ in symbols]
    # One addr2line process for the whole table: two output lines per address.
    output = run(["addr2line", "-e", kernel, "-f", "-C"] + addresses).splitlines()

    entries = []
    for index, (addr, name) in enumerate(symbols):
        offset = index * 2
        path = "unknown"
        line = 0
        if offset + 1 < len(output):
            path, line = split_location(output[offset + 1])
            path = normalize_file(path)
        entries.append((addr, c_string(name), c_string(path), line))
    return entries


def main():
    kernel, out_dir, limit, force_empty = parse_args(sys.argv)
    os.makedirs(out_dir, exist_ok=True)

    header_path = os.path.join(out_dir, "crash_symbols.h")
    data_path = os.path.join(out_dir, "crash_symbols.c")

    # The header is written first and is kernel-independent: build/kernel.o
    # depends on it, so it must exist even on a fresh tree.
    write_if_changed(header_path, header_text(limit))

    entries = []
    if not force_empty and os.path.isfile(kernel):
        entries = resolve_symbols(kernel, collect_symbols(kernel, limit))

    changed = write_if_changed(data_path, data_text(entries, limit))
    if changed:
        print("crash symbol table: %d symbols" % len(entries))
    return 0


if __name__ == "__main__":
    sys.exit(main())
